### ISSUE TITLE
NXP i.MX 8M SoC

### ISSUE THREAD

**Issue by jeremyhahn** [usbarmory/GoTEE#2]
Does GoTEE work with ARM Cortex-A53, NXP i.MX 8M SoC's like the ones found in the Google Coral dev board? If so, are there any issues to be aware of? If not, are there plans to support it? Thanks

**Comment by abarisani** [comment]
The only supported hardware is the one listed in the [Supported hardware](https://github.com/usbarmory/GoTEE?tab=readme-ov-file#supported-hardware). We cannot comment on future plans. Thanks.
